name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node Version
        run: node -v
      - name: Step with docker
        uses: docker://node:13.5.0-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node Version
        uses: docker://node:13.5.0-alpine3.10
        with: 
          entrypoint: /usr/local/bin/node
          args: '-v'
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release 